update docker

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,83 +1,155 @@
-# Server RMF with simulation
+FROM osrf/ros:jazzy-desktop-full
 
-# add AS builder to have a build enviroment see internet about
-ARG rosimage=osrf/ros:jazzy-desktop-full
+# Set up dev packages
+ENV DEBIAN_FRONTEND=noninteractive
+RUN apt-get update \
+   && apt-get -y install --no-install-recommends \
+    bash-completion \
+    gdb \
+    gettext-base \
+    git-core \
+    openssh-client \
+    python3-argcomplete \
+    python3-colcon-common-extensions \
+    python3-rosdep \
+    python3-vcs2l \
+    sudo \
+    # For GUI
+    libx11-xcb1 libxcb1 libxcb-render0 libxcb-shm0 libxcb-xfixes0 libxcb-shape0 \
+    libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-util1 \
+    libxcb-xinerama0 libxcb-xkb1 libxkbcommon0 libxkbcommon-x11-0 \
+    libglu1-mesa libxi6 libsm6 libxrender1 libfontconfig1 \
+   # Clean up
+    && apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
+ENV DEBIAN_FRONTEND=dialog
 
-FROM $rosimage
+### For Windows, uncomment the following lines to install WSLg dependencies and utilize vGPU acceleration 
+# ENV DEBIAN_FRONTEND=noninteractive
+# RUN apt-get update \
+#    && apt-get -y install \
+#           vainfo \
+#           mesa-va-drivers \
+#           mesa-utils \
+#    # Clean up
+#         && apt-get autoremove -y \
+#         && apt-get clean -y \
+#         && rm -rf /var/lib/apt/lists/*
+# ENV LIBVA_DRIVER_NAME=d3d12
+# ENV LD_LIBRARY_PATH=/usr/lib/wsl/lib
+# CMD vainfo --display drm --device /dev/dri/card0
+# ENV DEBIAN_FRONTEND=dialog
 
-#install develepment tool
-RUN apt update && apt install -y ros-dev-tools vim tmux git \
-    && rosdep update
-    # && rosdep init  
-    # && colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml \
-    # && colcon mixin update default
+################
+# uncomment below for nvidia support
+# Expose the nvidia driver to allow opengl 
+# Dependencies for glvnd and X11.
+################
+RUN apt-get update \
+ && apt-get install -y -qq --no-install-recommends \
+  libglvnd0 \
+  libgl1 \
+  libglx0 \
+  libegl1 \
+  libxext6 \
+  libx11-6 \
+&& rm -rf /var/lib/apt/lists/*
 
-#install Core rmf source
-# RUN mkdir -p ~/openRMF_ws/src \
-#     && apt update \
-#     && apt upgrade -y  && apt install -y wget python3-pip python3-vcstool ros-jazzy-rmw-cyclonedds-cpp \
-#     && pip3 install nudged eclipse-zenoh==1.5.0 pycdr2 rosbags --break-system-packages \
-#     && echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp\nsource /opt/ros/jazzy/setup.bash" >> ~/.bashrc \
-#     && /bin/bash -c "source /opt/ros/jazzy/setup.bash" \
-#     && wget https://raw.githubusercontent.com/open-rmf/rmf/jazzy/rmf.repos \
-#     && vcs import ~/openRMF_ws/src < rmf.repos \
-#     && cd ~/openRMF_ws \
-#     && rosdep install --from-paths src --ignore-src --rosdistro jazzy -yr \
-#     && /bin/bash -c "source /opt/ros/jazzy/setup.bash; colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release" \
-#     && rm -rf /var/lib/apt/lists/*
+# Env vars for the nvidia-container-runtime.
+ENV NVIDIA_VISIBLE_DEVICES=all
+ENV NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute
 
-#install Core rmf binary
-RUN apt update \
-    && apt upgrade -y  && apt install -y wget python3-pip python3-vcstool ros-jazzy-rmw-cyclonedds-cpp \
+ENV QT_X11_NO_MITSHM=1
+
+# ** [Optional] Uncomment this section to install additional packages. **
+#
+# ENV DEBIAN_FRONTEND=noninteractive
+# RUN apt-get update \
+#    && apt-get -y install --no-install-recommends <your-package-list-here> \
+#    #
+#    # Clean up
+#    && apt-get autoremove -y \
+#    && apt-get clean -y \
+#    && rm -rf /var/lib/apt/lists/*
+# ENV DEBIAN_FRONTEND=dialog
+
+# Set up auto-source of workspace for ros 
+ARG USERNAME=ros
+ARG USER_UID=1000
+ARG USER_GID=$USER_UID
+
+# Find and replace any user with matching UID
+RUN set -eux; \
+    existing_user=$(getent passwd "$USER_UID" | cut -d: -f1 || true); \
+    if [ -n "$existing_user" ]; then \
+        usermod -l $USERNAME -d /home/$USERNAME -m $existing_user && \
+        groupmod -n $USERNAME $existing_user && \
+        echo "Renamed $existing_user to $USERNAME"; \
+    else \
+        groupadd --gid $USER_GID $USERNAME && \
+        useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME && \
+        echo "Created new user $USERNAME"; \
+    fi
+# Ensure necessary directories and permissions
+RUN mkdir -p /home/$USERNAME /run/user/$USER_UID && \
+    chown -R $USER_UID:$USER_GID /home/$USERNAME /run/user/$USER_UID
+
+# Add sudo support for the non-root user
+RUN echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
+    && chmod 0440 /etc/sudoers.d/$USERNAME \
+    && touch /home/$USERNAME/.sudo_as_admin_successful
+
+# Set up autocompletion for user
+RUN  echo "if [ -f /opt/ros/${ROS_DISTRO}/setup.bash ]; then source /opt/ros/${ROS_DISTRO}/setup.bash; fi" >> /home/$USERNAME/.bashrc \
+  && echo "if [ -f /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash ]; then source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash; fi" >> /home/$USERNAME/.bashrc \
+  && echo "if [ -f /usr/share/vcs2l-completion/vcs.bash ]; then source /usr/share/vcs2l-completion/vcs.bash; fi" >> /home/$USERNAME/.bashrc \
+  # Set up auto-source of workspace for user
+  && echo "if [ -f ${WORKSPACE}/install/setup.bash ]; then source ${WORKSPACE}/install/setup.bash; fi" >> /home/$USERNAME/.bashrc
+
+# Set up python symlinks for vscode paths
+RUN PYTHON_VERSION=$(python3 -c "import sys; print(f'{sys.version_info[0]}.{sys.version_info[1]}')") \
+ && tgt="/opt/ros/${ROS_DISTRO}/lib/python${PYTHON_VERSION}/site-packages" \
+ && [ -d "$tgt" ] && ln -s "$tgt" "/opt/ros/${ROS_DISTRO}/lib/ros_site_packages"
+
+ENV AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS=1
+
+
+###########################################################
+
+RUN apt-get update \
+    && apt-get upgrade -y  && apt-get -y install --no-install-recommends wget python3-pip python3-vcstool ros-jazzy-rmw-cyclonedds-cpp \
     && pip3 install nudged eclipse-zenoh==1.5.0 pycdr2 rosbags --break-system-packages \
-    && echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp\nsource /opt/ros/jazzy/setup.bash" >> ~/.bashrc \
+    && echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp\nsource /opt/ros/jazzy/setup.bash" >> /home/$USERNAME/.bashrc \
     && apt install -y ros-jazzy-rmf-dev \
+    && apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN apt update && apt install -y ros-jazzy-nav2-bringup \
+    && git clone -b jazzy https://github.com/ROBOTIS-GIT/turtlebot3_simulations /home/$USERNAME/turtlebot3_simulations \
+    && echo "export TURTLEBOT3_MODEL=waffle\nexport GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/home/$USERNAME/turtlebot3_simulations/turtlebot3_gazebo/models" >> /home/$USERNAME/.bashrc \
     && rm -rf /var/lib/apt/lists/*
 
 
-# # #install simulation code
-RUN apt update && apt install -y ros-jazzy-nav2-bringup git \
-    && git clone -b jazzy https://github.com/ROBOTIS-GIT/turtlebot3_simulations ~/turtlebot3_simulations \
-    && echo "export TURTLEBOT3_MODEL=waffle\nexport GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:~/turtlebot3_simulations/turtlebot3_gazebo/models" >> ~/.bashrc \
-    && rm -rf /var/lib/apt/lists/*
-
-# # #install zenoh
-RUN echo "deb [trusted=yes] https://download.eclipse.org/zenoh/debian-repo/ /" | sudo tee -a /etc/apt/sources.list > /dev/null \
+RUN curl -L https://download.eclipse.org/zenoh/debian-repo/zenoh-public-key | sudo gpg --dearmor --yes --output /etc/apt/keyrings/zenoh-public-key.gpg \
+    && echo "deb [signed-by=/etc/apt/keyrings/zenoh-public-key.gpg] https://download.eclipse.org/zenoh/debian-repo/ /" | sudo tee -a /etc/apt/sources.list > /dev/null \
     && apt update \
-    && apt install -y systemctl zenoh \
+    && apt install -y systemctl zenoh unzip \
     && rm -rf /var/lib/apt/lists/*
 
-#install free fleet and personal code
-
-RUN mkdir -p ~/openRMF_ws
+RUN mkdir -p /home/$USERNAME/openRMF_ws
 
 RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
 
-RUN --mount=type=ssh git clone -b master --recurse-submodules git@github.com:michbelle/tesi_mag.git ~/openRMF_ws
+RUN --mount=type=ssh git clone -b master --recurse-submodules git@github.com:michbelle/tesi_mag.git /home/$USERNAME/openRMF_ws
 
 RUN apt update \
-    && cd ~/openRMF_ws \
+    && cd /home/$USERNAME/openRMF_ws \
     && rosdep install --from-paths src --ignore-src --rosdistro jazzy -yr \
     && /bin/bash -c "source /opt/ros/jazzy/setup.bash; colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release" \
-    && echo "source ~/openRMF_ws/install/setup.bash" >> ~/.bashrc
+    && echo "source /home/$USERNAME/openRMF_ws/install/setup.bash" >> /home/$USERNAME/.bashrc
+    
+###########################################################
 
-#install D-start-trajectory-planner
-# RUN cd ~/openRMF_ws/src \
-#     && git clone -b jazzy https://github.com/ElettraSciComp/DStar-Trajectory-Planner.git \
-#     && apt update \
-#     && cd ~/openRMF_ws \
-#     && rosdep install --from-paths src --ignore-src --rosdistro jazzy -yr \
-#     && /bin/bash -c "source /opt/ros/jazzy/setup.bash; colcon build --symlink-install --packages-select dstar_global_planner --cmake-args -DCMAKE_BUILD_TYPE=Release" 
 
-# #install tesi code
-# RUN cd ~/openRMF_ws/src \
-#     && git clone -b master https://github.com/michbelle/myTesiCode.git \
-#     && apt update \
-#     && cd ~/openRMF_ws \
-#     && rosdep install --from-paths src --ignore-src --rosdistro jazzy -yr \
-#     && echo "export GZ_SIM_RESOURCE_PATH=$GZ_SIM_RESOURCE_PATH:/root/openRMF_ws/src/myTesiCode/rmf_code/ign_world/elettra/modelOUT/" >> ~/.bashrc \
-#     && /bin/bash -c "source /opt/ros/jazzy/setup.bash; colcon build --symlink-install --packages-select myCode" \
-#     && echo "source ~/openRMF_ws/install/setup.bash" >> ~/.bashrc
-
-# #set simulation robot for nav2
-# ENV TURTLEBOT3_MODEL=burger
